### PR TITLE
convert forIn to forEach

### PR DESCRIPTION
**Pull request by Chiragmodi1247**
*Issue #302 , if available:*

*Description of changes:*
refactor: converting all _.forIn to Combination of object.keys and forEach

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chazzmoney** [comment]
Hey, thanks for your contribution!

It looks like there were some formatting changes (single/double quotes), commas, semicolons here - can we remove those from the PR? You can suggest those changes in a separate PR from the conversion of forIn to forEach.

Thanks!

**Comment by chazzmoney** [comment]
@Chiragmodi1247 Are you still working on this? Would love to merge this in.

**Comment by dbanksdesign** [comment]
@Chiragmodi1247 just checking in on this. Let me know if you need any help!

**Comment by dbanksdesign** [comment]
Closing this due to inactivity. Feel free to re-open.

**Pull request closed without merging**
