### PR TITLE
chore(tests): Fix test titles

### PR DESCRIPTION
**Pull request by jessicalynch**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jorenbroekema — APPROVED** [review]
Ah thanks, I must have done a find & replace at some point converting "var" to "const" and accidentally applied it to these 😓

**Comment by jessicalynch** [comment]
> Ah thanks, I must have done a find & replace at some point converting "var" to "const" and accidentally applied it to these 😓 

I suspected that's what happened... relatable :)

**Comment by jorenbroekema** [comment]
@jessicalynch btw I saw your tailwind example PR as well, gonna review that ASAP, just been really busy lately and actually got a lot of issues/PRs here recently (which is a good thing!!) so I haven't been as responsive as I usually am

**Review by dbanksdesign — APPROVED** [review]
😆

**Pull request merged**
