### PR TITLE
test(all): Fix for all tests to match the date and remove of mockdate

### PR DESCRIPTION
**Pull request by davixyz**
*Issue #, if available:*

*Description of changes:*

Tried to run the project, failed some tests went ahead and fixed it. I see that there were a lot of changes around of this, is this the right solution? seems to pass for now.

I checked in the package.json and package-lock.json since I removed mockdate but I could remove these from the PR if needed.

inspiration https://github.com/facebook/jest/issues/2234

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dbanksdesign** [comment]
@didoo thoughts? Looks good to me!

**Comment by chazzmoney** [comment]
LGTM 🎉

**Comment by didoo** [comment]
I don't understand how, but it works! Well done @davixyz 👏 
(you also catched a couple of oversights by me)

**Comment by chazzmoney** [comment]
Woooo! Nice work @davixyz 🎉

**Comment by davixyz** [comment]
Yay! 🎉

**Pull request merged**
