### PR TITLE
ci: add support for node v10 & v12, remove v6

### PR DESCRIPTION
**Pull request by dishankmehta**
*Issue #, if available:*
302

*Description of changes:*
Removed support for node v6. Added node v10 & v12

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dbanksdesign** [comment]
Some data for this, Node v8 will end its long-term support by the end of this year. Node v6 is already past long-term support and AWS Lambda no longer supports v6 as a runtime. 

https://nodejs.org/en/about/releases/
https://nodejs.org/metrics/

**Comment by dbanksdesign** [comment]
@dishankmehta we should probably update the engines attribute in the package.json file to show support for >= 8 rather than 6 as well.

**Comment by dishankmehta** [comment]
@dbanksdesign Sure. On it.

**Comment by dishankmehta** [comment]
Done. Updated the engines attribute in package.json for node >=8.

**Pull request merged**
