### PR TITLE
feat: react-native support

### PR DESCRIPTION
**Pull request by levi-pires**
*Issue #, if available:* #497

*Description of changes:* Added support to React Native

```js
// lib/common/transformGroups.js
'react-native': [
    'name/cti/camel',
    'size/object',
    'color/css'
  ]
```

```js
// lib/common/transforms.js
"size/object": {
    type: "value",
    matcher: isSize,
    transformer: function (prop, options) {
      var val = parseFloat(prop.value);
      if (isNaN(val)) throwSizeError(prop.name, prop.value, "object");

      return {
        original: prop.value,
        number: val,
        decimal: val / 100,
        scale: val * getBasePxFontSize(options),
      };
    },
  }
```
*Example:*

```js
// examples/advanced/create-react-native-app/src/App.js
import { StatusBar } from "expo-status-bar";
import React from "react";
import { StyleSheet, Text, View, PixelRatio } from "react-native";
import * as variables from "./style-dictionary-dist/variables";

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Testing! Testing!</Text>
      <Text style={styles.p}>All done!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: variables.colorBrand01,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: PixelRatio.getFontScale() * variables.sizeFontMd.scale,
    color: variables.colorBrand02,
  },
  p: {
    fontSize: PixelRatio.getFontScale() * variables.sizeFontSm.number,
    color: variables.colorBrand02,
  },
});
```

```js
// examples/advanced/create-react-native-app/src/style-dictionary-dist/variables.js
export const colorBrand01 = "#eeeeff";
export const colorBrand02 = "#ddaa33";
export const sizeFontSm = {"original":"16px","number":16,"decimal":0.16,"scale":256};
export const sizeFontMd = {"original":"2rem","number":2,"decimal":0.02,"scale":32};
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chazzmoney** [comment]
Thank you for putting this together @levi-pires 

At first glance it looks pretty good. Danny and I will try to do a more in depth review here soon.

Appreciate your contribution!

**Comment by chazzmoney** [comment]
Hi again @levi-pires 

This is great!

A few requests:
- Can you add unit tests to '' for the 'size/object' transform
- Can you add unit tests to '' for the 'react-native' transformGroup
- Can you use the 'getBasePxFontSize' function on line 59 of transform instead of using a fixed 16 in the scaling part of the 'size/object' transform

Looking good!

**Comment by levi-pires** [comment]
@chazzmoney

Almost all done! I just need to know where I can put the unit test for the transformGroup

**Comment by chazzmoney** [comment]
Wow - fast response! 👍 

Thanks, this looks great to me.

@dbanksdesign any concerns? Otherwise, I'm :shipit:

**Review by dbanksdesign — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
