### PR TITLE
fix(sketch): fix sketch palette format to use new filters

### PR DESCRIPTION
**Pull request by dbanksdesign**
*Issue #, if available:* #285

*Description of changes:* Removing filtering from the sketch/palette format because we handle filtering before formats now.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dbanksdesign** [comment]
There is a new version of the sketchpalette plugin, and I can't get the old version to work. I'm thinking to not break backwards compatibility, we could instead create a new format with 'sketch/palette/v2'?

**Comment by chazzmoney** [comment]
👍🏾

**Comment by custa1200** [comment]
I agree with the idea to create a new one is probably the best path forward. The naming is something I think we'd need in Sketch Palettes, I can see no value in putting effort into the old one. Unfortunately I had to park my SD integration for the moment so can't get back to look at it this sprint.

**Comment by chazzmoney** [comment]
LGTM :shipit:

**Pull request merged**
