### PR TITLE
2.4 release

### PR DESCRIPTION
**Pull request by chazzmoney**
Just merged Master into develop, and then made a couple small changes. Thought I would try to sync these minor changes back to master. These changes are silly, so wanted to submit a PR instead of just pushing.

Atom added newlines to the end of the JSON files. Looks like JSON files should have a newline character at the end (https://github.com/serverless/serverless/issues/1321).

Also removed the unused fs module from the filterProperties test script.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chazzmoney** [comment]
GRRRRRRrrrrrr. The rebase from master into develop is now generating conflicts with master...

**Comment by chazzmoney** [comment]
If we decide to add this, lets do it as a squash and merge.

**Comment by dbanksdesign** [comment]
Was this merged in already? The develop branch looks up to date

**Comment by chazzmoney** [comment]
The develop branch is up-to-date, and I made a few additional changes, which you can see in the files changed section. I don't know why it thinks those other changes are part of this, which is why we would need to do a squash and merge instead of rebase and merge.

**Comment by dbanksdesign** [comment]
The only real change I see is removing line 16 in test/filterProperties.js, is that it?

**Comment by chazzmoney** [comment]
Woohoo!

**Pull request merged**
