### PR TITLE
Remove word simply

### PR DESCRIPTION
**Pull request by Iqlaas**
*Issue #, if available:*
#328 
*Description of changes:*
Remove word _simply_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dbanksdesign** [comment]
Hey @Iqlaas we are just waiting for a larger documentation update PR to get finished and merged in before this one.

**Comment by Iqlaas** [comment]
thanks @dbanksdesign . appreciate it  🥇

**Comment by dbanksdesign** [comment]
We just merged a large PR with documentation edits. @Iqlaas could you rebase and fix any conflicts please. Thank you!

**Comment by dbanksdesign** [comment]
Closing this as there are no longer relevant changes after the rebase. Thank you for your work on this though and feel free to suggest any other improvements to the docs or the framework!

**Pull request closed without merging**
