### PR TITLE
feat(examples): add tailwind preset example

### PR DESCRIPTION
**Pull request by jessicalynch**
*Description of changes:*

Adds example for building a [Tailwind preset](https://tailwindcss.com/docs/presets#creating-a-preset) from tokens.

`// demo/index.html`

Screenshot 2023-10-30 at 10 11 02 PM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by beejsbj** [comment]
An update on when this will be merged?

**Comment by jorenbroekema** [comment]
Hi, we're working hard on a v4 major release of style-dictionary, which already has some stable prereleases out there. 
I'd love to give this a full review and merge this to the v4 branch if you're willing to rebase this to v4. We're putting v3 in maintenance mode which means we're only looking to merge important bugfixes or security vulnerabilities.

[The changelog for v4](https://github.com/amzn/style-dictionary/blob/v4/CHANGELOG.md) so far will be important to go over as there are some breaking changes to Style-Dictionary in v4 that affects your example.

**Comment by jessicalynch** [comment]
Thanks, that sounds great -- I will review the changelog and rebase to v4.

**Comment by jorenbroekema** [comment]
Aah I think this PR was closed when we merged the v4 to main and released 4.0.0, because I then removed the v4 branch, feel free to open a new PR on the main branch and let me know if you need anything from my side to get this contribution to the finish line! :)

**Pull request closed without merging**
