### PR TITLE
add typescript declarations formats

### PR DESCRIPTION
**Pull request by Tiamanti**
*Issue #425 

*Description of changes:*
feat(formats): add typescript/es6-declarations formats for .d.ts
feat(formats): add typescript/module-declarations formats for .d.ts

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Tiamanti** [comment]
@chazzmoney Could you take a look at it?
Fail on Node 8 is related to Jest which [does not support Node 8](https://github.com/facebook/jest/blob/master/package.json#L146) in the version used in project.

This is also a duplicate with extension of https://github.com/amzn/style-dictionary/pull/467 as the PR seems dead.

**Comment by chazzmoney** [comment]
Thanks for this @Tiamanti 

Can you do it off of branch 3.0 instead of main? I know its confusing at the moment, but we won't be merging much of anything into main anymore besides documentation about 3.0. It should also get you on the right checks.

**Comment by chazzmoney** [comment]
the changes look good to me, though my typescript knowledge is not as strong as yours I'm sure

**Comment by chazzmoney** [comment]
Hi @Tiamanti 

Just wanted to see if you were working on a 3.0 branch version of this? I was assuming so because of the thumbs up emoji you sent, but wanted to clarify.

Thanks!

**Comment by chazzmoney** [comment]
Hi @Tiamanti I switched it to 3.0 to clarify that is where it will be merged when ready.

**Pull request closed without merging**
