### PR TITLE
feat(formats): javascript/module-flat format

### PR DESCRIPTION
**Pull request by noslouch**
*Description of changes:*
Adds a new `javascript/module-flat` format that's just like the `json/flat` format, but exported as a cjs module. We have a use case in a project, and this seemed generic enough to consider for the core.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by noslouch** [comment]
bump

**Comment by dbanksdesign** [comment]
Sorry for the lateness of this review. This looks great! I changed the branch to 3.0 since that will be the next release. Thank you for your contribution!

**Review by dbanksdesign — APPROVED** [review]

**Comment by chazzmoney** [comment]
LGTM! :shipit:

**Comment by noslouch** [comment]
thanks!

**Pull request merged**
