### PR TITLE
Merge Jest Branch

### PR DESCRIPTION
**Pull request by chazzmoney**
Should this go to develop or develop-3.0?

### CODE REVIEW

**Comment by dbanksdesign** [comment]
Because this shouldn't have any effect for end-users, I think this is ok to go into develop to go out in the 2.5 release.

**Comment by chazzmoney** [comment]
Sounds good. Will resolve conflicts on Friday.

**Comment by didoo** [comment]
@chazzmoney I am super-busy in these days, sorry. if you can resolve the conflicts, that would be great
@dbanksdesign I was thinking exactly the same yesterday morning while walking to work. so +1, let's merge to master, we can always improve and tune later, there's no risk of impact on the end users

**Comment by chazzmoney** [comment]
So I'm clearly doing something wrong in merging the json5 PR here @vvscode. Do you see what mistake I made?

**Comment by vvscode** [comment]
It's jest specific issue

@chazzmoney  https://github.com/amzn/style-dictionary/pull/173

**Pull request merged**
